#!/usr/bin/env python3
"""Reproject Planck dust-model HEALPix columns onto the DFUWS radiance WCS."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from astropy.coordinates import Galactic
from astropy.io import fits
from astropy.wcs import WCS
from reproject import reproject_from_healpix


PLANCK_COLUMNS = {
    "EBV": ("planck_ebv.fits.fz", "mag", "Planck E(B-V)"),
    "TEMP": ("planck_temperature.fits.fz", "K", "Planck dust temperature"),
    "TAU353": ("planck_tau353.fits.fz", "", "Planck optical depth tau_353"),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate DFUWS-grid Planck E(B-V), temperature, and tau_353 maps."
    )
    parser.add_argument(
        "--planck-model",
        type=Path,
        default=Path("/Users/qliu/data/dust/HFI_CompMap_ThermalDustModel_2048_R1.20.fits"),
        help="Planck HFI thermal dust model HEALPix FITS table.",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=Path("/Users/qliu/dragonfly/cirrus/outputs/mosaics/dfuws/planck_radiance.fits"),
        help="Reference image whose WCS and shape define the output grid.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/Users/qliu/dragonfly/cirrus/outputs/mosaics/dfuws"),
        help="Directory for generated compressed FITS images.",
    )
    parser.add_argument("--overwrite", action="store_true", help="Replace existing generated maps.")
    return parser.parse_args()


def reference_grid(path: Path) -> tuple[fits.Header, WCS, tuple[int, int]]:
    with fits.open(path, memmap=True) as hdul:
        hdu = next((item for item in hdul if item.data is not None), None)
        if hdu is None:
            raise ValueError(f"No image data found in {path}")
        header = hdu.header.copy()
        shape = tuple(int(value) for value in hdu.data.shape[-2:])
    return header, WCS(header).celestial, shape


def write_compressed_image(path: Path, data: np.ndarray, header: fits.Header, unit: str, comment: str) -> None:
    image_header = header.copy()
    image_header["BUNIT"] = unit
    image_header["BTYPE"] = comment
    image_header.add_history("Generated by scripts/build_dfuws_planck_dust_maps.py")
    hdu = fits.CompImageHDU(data=np.asarray(data, dtype=np.float32), header=image_header, name="IMAGE")
    fits.HDUList([fits.PrimaryHDU(), hdu]).writeto(path, overwrite=True)


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    reference_header, reference_wcs, shape = reference_grid(args.reference)

    with fits.open(args.planck_model, memmap=True) as hdul:
        table = hdul["COMP-MAP"].data
        available = set(table.columns.names)
        missing = sorted(set(PLANCK_COLUMNS) - available)
        if missing:
            raise KeyError(f"Planck model is missing required columns: {', '.join(missing)}")

        for column, (filename, fallback_unit, comment) in PLANCK_COLUMNS.items():
            output_path = args.output_dir / filename
            if output_path.exists() and not args.overwrite:
                print(f"Skipping existing {output_path}")
                continue

            field = np.asarray(table[column], dtype=np.float32)
            array, footprint = reproject_from_healpix(
                (field, Galactic()),
                reference_wcs,
                shape_out=shape,
                nested=True,
            )
            array = np.asarray(array, dtype=np.float32)
            array[footprint <= 0] = np.nan
            unit = str(table.columns[column].unit or fallback_unit or "").strip()
            if unit == "none":
                unit = ""
            write_compressed_image(output_path, array, reference_header, unit, comment)
            finite = np.isfinite(array)
            if finite.any():
                lo, hi = np.nanpercentile(array[finite], [1, 99])
                print(f"Wrote {output_path} ({unit or 'dimensionless'}), q01={lo:.6g}, q99={hi:.6g}")
            else:
                print(f"Wrote {output_path} ({unit or 'dimensionless'}), no finite pixels")


if __name__ == "__main__":
    main()
